manifest = {
  config: {
    width: "300",
    height: "600",
    clickTag: "#",
  },
  stageObjects: [
    {
      element: ".background",
      type: "div",
      x: 0,
      y: 0,
      width: 300,
      height: 600,
      attributes: { style: "background: linear-gradient(to bottom, #00d0ff 0%,#ffffff 50%,#ffc279 75%,#fea086 100%);" },
    },
    {
      element: ".poster",
      type: "img",
      x: 0,
      y: 66,
      width: 300,
      height: 424,
      attributes: { src: "./images/poster.jpg" },
    },
    {
      element: ".planYourTrip",
      type: "img",
      x: 59,
      y: 503,
      width: 180,
      height: 50,
      attributes: { src: "./images/button.png" },
    },
    {
      element: ".visitParadise",
      type: "img",
      x: 12,
      y: 284,
      width: 275,
      height: 55,
      attributes: { src: "./images/title.png" },
    },
    {
      element: ".copyright",
      type: "img",
      x: 22,
      y: 582,
      width: 256,
      height: 10,
      attributes: { src: "./images/Copyright.png" },
    },
    {
      element: ".logo",
      type: "img",
      x: 105,
      y: 562,
      width: 90,
      height: 15,
      attributes: { src: "./images/logo.png" },
    },
    {
      element: ".tagline",
      type: "img",
      x: 19,
      y: 10,
      width: 262,
      height: 48,
      attributes: { src: "./images/tagline.png" },
    },
  ],
};

module.exports = manifest;
